# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'framelesswidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FramelessWidget(object):
    def setupUi(self, FramelessWidget):
        FramelessWidget.setObjectName("FramelessWidget")
        FramelessWidget.resize(649, 619)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FramelessWidget.sizePolicy().hasHeightForWidth())
        FramelessWidget.setSizePolicy(sizePolicy)
        FramelessWidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(FramelessWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.windowFrame = QtWidgets.QWidget(FramelessWidget)
        self.windowFrame.setObjectName("windowFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.windowFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowTitlebar = QtWidgets.QWidget(self.windowFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.windowTitlebar.sizePolicy().hasHeightForWidth())
        self.windowTitlebar.setSizePolicy(sizePolicy)
        self.windowTitlebar.setMinimumSize(QtCore.QSize(0, 40))
        self.windowTitlebar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.windowTitlebar.setObjectName("windowTitlebar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.windowTitlebar)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_icon = QtWidgets.QLabel(self.windowTitlebar)
        self.label_icon.setMinimumSize(QtCore.QSize(24, 24))
        self.label_icon.setMaximumSize(QtCore.QSize(24, 24))
        self.label_icon.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout_2.addWidget(self.label_icon)
        self.label_title = QtWidgets.QLabel(self.windowTitlebar)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_data = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_data.setText("")
        self.toolButton_data.setObjectName("toolButton_data")
        self.horizontalLayout.addWidget(self.toolButton_data)
        self.toolButton_full_exit = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_full_exit.setText("")
        self.toolButton_full_exit.setObjectName("toolButton_full_exit")
        self.horizontalLayout.addWidget(self.toolButton_full_exit)
        self.toolButton_full = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_full.setText("")
        self.toolButton_full.setObjectName("toolButton_full")
        self.horizontalLayout.addWidget(self.toolButton_full)
        self.toolButton_min = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_min.setText("")
        self.toolButton_min.setObjectName("toolButton_min")
        self.horizontalLayout.addWidget(self.toolButton_min)
        self.toolButton_restore = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_restore.setText("")
        self.toolButton_restore.setObjectName("toolButton_restore")
        self.horizontalLayout.addWidget(self.toolButton_restore)
        self.toolButton_max = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_max.setText("")
        self.toolButton_max.setObjectName("toolButton_max")
        self.horizontalLayout.addWidget(self.toolButton_max)
        self.toolButton_close = QtWidgets.QToolButton(self.windowTitlebar)
        self.toolButton_close.setText("")
        self.toolButton_close.setObjectName("toolButton_close")
        self.horizontalLayout.addWidget(self.toolButton_close)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.windowTitlebar)
        self.windowContent = QtWidgets.QWidget(self.windowFrame)
        self.windowContent.setObjectName("windowContent")
        self.verticalLayout.addWidget(self.windowContent)
        self.gridLayout.addWidget(self.windowFrame, 0, 0, 1, 1)

        self.retranslateUi(FramelessWidget)
        QtCore.QMetaObject.connectSlotsByName(FramelessWidget)

    def retranslateUi(self, FramelessWidget):
        _translate = QtCore.QCoreApplication.translate
        FramelessWidget.setWindowTitle(_translate("FramelessWidget", "FramelessWidget"))
        self.label_title.setText(_translate("FramelessWidget", "Polaris"))

import images_rc
